//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCharging
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargingNows
    {
        public int ID_Charging { get; set; }
        public int ID_Driver { get; set; }
        public int ID_Car { get; set; }
        public int ID_Charger { get; set; }
        public double ProbabilitySecond { get; set; }
        public System.DateTime TimeStartCharging { get; set; }
        public System.DateTime TimeEndChargingExpect { get; set; }
    
        public virtual Chargers Chargers { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
