//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCharging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chargers
    {
        public Chargers()
        {
            this.ChargingNow = new HashSet<ChargingNows>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Charger { get; set; }
        public string ChargerName { get; set; }
        public string ChargerAddress { get; set; }
        public string ChargerGPS { get; set; }
        public string ChargerStatus { get; set; }
        public int NumAllPlaces { get; set; }
        public int NumEmptyPlaces { get; set; }
        public int NumOrderPlaces { get; set; }
    
        public virtual ICollection<ChargingNows> ChargingNow { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
