//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCharging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public Drivers()
        {
            this.Cars = new HashSet<Cars>();
            this.ChargingNow = new HashSet<ChargingNows>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Driver { get; set; }
        public string DriverName { get; set; }
        public string DriverLogin { get; set; }
        public string DriverPassword { get; set; }
        public int Age { get; set; }
        public string DriverStatus { get; set; }
        public double Probability { get; set; }
    
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual ICollection<ChargingNows> ChargingNow { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
