//#pragma warning disable 1591
////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CarCharging
//{
//    using System.Data.Linq;
//    using System.Data.Linq.Mapping;
//    using System.Data;
//    using System.Collections.Generic;
//    using System.Reflection;
//    using System.Linq;
//    using System.Linq.Expressions;
//    using System.ComponentModel;
//    using System;
	
	
//    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarCharging")]
//    public partial class LinqDataContext : System.Data.Linq.DataContext
//    {
		
//        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
//    #region Extensibility Method Definitions
//    partial void OnCreated();
//    partial void InsertCar(Cars instance);
//    partial void UpdateCar(Cars instance);
//    partial void DeleteCar(Cars instance);
//    partial void InsertCharger(Chargers instance);
//    partial void UpdateCharger(Chargers instance);
//    partial void DeleteCharger(Chargers instance);
//    partial void InsertChargingNow(ChargingNows instance);
//    partial void UpdateChargingNow(ChargingNows instance);
//    partial void DeleteChargingNow(ChargingNows instance);
//    partial void InsertDriver(Drivers instance);
//    partial void UpdateDriver(Drivers instance);
//    partial void DeleteDriver(Drivers instance);
//    partial void InsertOrder(Orders instance);
//    partial void UpdateOrder(Orders instance);
//    partial void DeleteOrder(Orders instance);
//    #endregion
		
//        public LinqDataContext() : 
//                base(global::CarCharging.Properties.Settings.Default.CarChargingConnectionString, mappingSource)
//        {
//            OnCreated();
//        }
		
//        public LinqDataContext(string connection) : 
//                base(connection, mappingSource)
//        {
//            OnCreated();
//        }
		
//        public LinqDataContext(System.Data.IDbConnection connection) : 
//                base(connection, mappingSource)
//        {
//            OnCreated();
//        }
		
//        public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//                base(connection, mappingSource)
//        {
//            OnCreated();
//        }
		
//        public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//                base(connection, mappingSource)
//        {
//            OnCreated();
//        }
		
//        public System.Data.Linq.Table<Cars> Cars
//        {
//            get
//            {
//                return this.GetTable<Cars>();
//            }
//        }
		
//        public System.Data.Linq.Table<Chargers> Chargers
//        {
//            get
//            {
//                return this.GetTable<Chargers>();
//            }
//        }
		
//        public System.Data.Linq.Table<ChargingNows> ChargingNows
//        {
//            get
//            {
//                return this.GetTable<ChargingNows>();
//            }
//        }
		
//        public System.Data.Linq.Table<Drivers> Drivers
//        {
//            get
//            {
//                return this.GetTable<Drivers>();
//            }
//        }
		
//        public System.Data.Linq.Table<Orders> Orders
//        {
//            get
//            {
//                return this.GetTable<Orders>();
//            }
//        }
//    }
	
//    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cars")]
//    public partial class Cars : INotifyPropertyChanging, INotifyPropertyChanged
//    {
		
//        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//        private int _ID_Car;
		
//        private int _ID_Driver;
		
//        private string _CarType;
		
//        private System.Nullable<double> _CarBatteryLevel;
		
//        private System.Nullable<double> _CarTimeToCharge;
		
//        private EntityRef<Drivers> _Driver;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnID_CarChanging(int value);
//    partial void OnID_CarChanged();
//    partial void OnID_DriverChanging(int value);
//    partial void OnID_DriverChanged();
//    partial void OnCarTypeChanging(string value);
//    partial void OnCarTypeChanged();
//    partial void OnCarBatteryLevelChanging(System.Nullable<double> value);
//    partial void OnCarBatteryLevelChanged();
//    partial void OnCarTimeToChargeChanging(System.Nullable<double> value);
//    partial void OnCarTimeToChargeChanged();
//    #endregion
		
//        public Cars()
//        {
//            this._Driver = default(EntityRef<Drivers>);
//            OnCreated();
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Car", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//        public int ID_Car
//        {
//            get
//            {
//                return this._ID_Car;
//            }
//            set
//            {
//                if ((this._ID_Car != value))
//                {
//                    this.OnID_CarChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Car = value;
//                    this.SendPropertyChanged("ID_Car");
//                    this.OnID_CarChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Driver", DbType="Int NOT NULL")]
//        public int ID_Driver
//        {
//            get
//            {
//                return this._ID_Driver;
//            }
//            set
//            {
//                if ((this._ID_Driver != value))
//                {
//                    if (this._Driver.HasLoadedOrAssignedValue)
//                    {
//                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//                    }
//                    this.OnID_DriverChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Driver = value;
//                    this.SendPropertyChanged("ID_Driver");
//                    this.OnID_DriverChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string CarType
//        {
//            get
//            {
//                return this._CarType;
//            }
//            set
//            {
//                if ((this._CarType != value))
//                {
//                    this.OnCarTypeChanging(value);
//                    this.SendPropertyChanging();
//                    this._CarType = value;
//                    this.SendPropertyChanged("CarType");
//                    this.OnCarTypeChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBatteryLevel", DbType="Float")]
//        public System.Nullable<double> CarBatteryLevel
//        {
//            get
//            {
//                return this._CarBatteryLevel;
//            }
//            set
//            {
//                if ((this._CarBatteryLevel != value))
//                {
//                    this.OnCarBatteryLevelChanging(value);
//                    this.SendPropertyChanging();
//                    this._CarBatteryLevel = value;
//                    this.SendPropertyChanged("CarBatteryLevel");
//                    this.OnCarBatteryLevelChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarTimeToCharge", DbType="Float")]
//        public System.Nullable<double> CarTimeToCharge
//        {
//            get
//            {
//                return this._CarTimeToCharge;
//            }
//            set
//            {
//                if ((this._CarTimeToCharge != value))
//                {
//                    this.OnCarTimeToChargeChanging(value);
//                    this.SendPropertyChanging();
//                    this._CarTimeToCharge = value;
//                    this.SendPropertyChanged("CarTimeToCharge");
//                    this.OnCarTimeToChargeChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_Car", Storage="_Driver", ThisKey="ID_Driver", OtherKey="ID_Driver", IsForeignKey=true)]
//        public Drivers Driver
//        {
//            get
//            {
//                return this._Driver.Entity;
//            }
//            set
//            {
//                Drivers previousValue = this._Driver.Entity;
//                if (((previousValue != value) 
//                            || (this._Driver.HasLoadedOrAssignedValue == false)))
//                {
//                    this.SendPropertyChanging();
//                    if ((previousValue != null))
//                    {
//                        this._Driver.Entity = null;
//                        previousValue.Cars.Remove(this);
//                    }
//                    this._Driver.Entity = value;
//                    if ((value != null))
//                    {
//                        value.Cars.Add(this);
//                        this._ID_Driver = value.ID_Driver;
//                    }
//                    else
//                    {
//                        this._ID_Driver = default(int);
//                    }
//                    this.SendPropertyChanged("Driver");
//                }
//            }
//        }
		
//        public event PropertyChangingEventHandler PropertyChanging;
		
//        public event PropertyChangedEventHandler PropertyChanged;
		
//        protected virtual void SendPropertyChanging()
//        {
//            if ((this.PropertyChanging != null))
//            {
//                this.PropertyChanging(this, emptyChangingEventArgs);
//            }
//        }
		
//        protected virtual void SendPropertyChanged(String propertyName)
//        {
//            if ((this.PropertyChanged != null))
//            {
//                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//            }
//        }
//    }
	
//    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chargers")]
//    public partial class Chargers : INotifyPropertyChanging, INotifyPropertyChanged
//    {
		
//        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//        private int _ID_Charger;
		
//        private string _ChargerName;
		
//        private string _ChargerAddress;
		
//        private string _ChargerGPS;
		
//        private string _ChargerStatus;
		
//        private int _NumAllPlaces;
		
//        private int _NumEmptyPlaces;
		
//        private int _NumOrderPlaces;
		
//        private EntitySet<ChargingNows> _ChargingNows;
		
//        private EntitySet<Orders> _Orders;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnID_ChargerChanging(int value);
//    partial void OnID_ChargerChanged();
//    partial void OnChargerNameChanging(string value);
//    partial void OnChargerNameChanged();
//    partial void OnChargerAddressChanging(string value);
//    partial void OnChargerAddressChanged();
//    partial void OnChargerGPSChanging(string value);
//    partial void OnChargerGPSChanged();
//    partial void OnChargerStatusChanging(string value);
//    partial void OnChargerStatusChanged();
//    partial void OnNumAllPlacesChanging(int value);
//    partial void OnNumAllPlacesChanged();
//    partial void OnNumEmptyPlacesChanging(int value);
//    partial void OnNumEmptyPlacesChanged();
//    partial void OnNumOrderPlacesChanging(int value);
//    partial void OnNumOrderPlacesChanged();
//    #endregion
		
//        public Chargers()
//        {
//            this._ChargingNows = new EntitySet<ChargingNows>(new Action<ChargingNows>(this.attach_ChargingNows), new Action<ChargingNows>(this.detach_ChargingNows));
//            this._Orders = new EntitySet<Orders>(new Action<Orders>(this.attach_Orders), new Action<Orders>(this.detach_Orders));
//            OnCreated();
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Charger", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//        public int ID_Charger
//        {
//            get
//            {
//                return this._ID_Charger;
//            }
//            set
//            {
//                if ((this._ID_Charger != value))
//                {
//                    this.OnID_ChargerChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Charger = value;
//                    this.SendPropertyChanged("ID_Charger");
//                    this.OnID_ChargerChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargerName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
//        public string ChargerName
//        {
//            get
//            {
//                return this._ChargerName;
//            }
//            set
//            {
//                if ((this._ChargerName != value))
//                {
//                    this.OnChargerNameChanging(value);
//                    this.SendPropertyChanging();
//                    this._ChargerName = value;
//                    this.SendPropertyChanged("ChargerName");
//                    this.OnChargerNameChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargerAddress", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
//        public string ChargerAddress
//        {
//            get
//            {
//                return this._ChargerAddress;
//            }
//            set
//            {
//                if ((this._ChargerAddress != value))
//                {
//                    this.OnChargerAddressChanging(value);
//                    this.SendPropertyChanging();
//                    this._ChargerAddress = value;
//                    this.SendPropertyChanged("ChargerAddress");
//                    this.OnChargerAddressChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargerGPS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string ChargerGPS
//        {
//            get
//            {
//                return this._ChargerGPS;
//            }
//            set
//            {
//                if ((this._ChargerGPS != value))
//                {
//                    this.OnChargerGPSChanging(value);
//                    this.SendPropertyChanging();
//                    this._ChargerGPS = value;
//                    this.SendPropertyChanged("ChargerGPS");
//                    this.OnChargerGPSChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargerStatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string ChargerStatus
//        {
//            get
//            {
//                return this._ChargerStatus;
//            }
//            set
//            {
//                if ((this._ChargerStatus != value))
//                {
//                    this.OnChargerStatusChanging(value);
//                    this.SendPropertyChanging();
//                    this._ChargerStatus = value;
//                    this.SendPropertyChanged("ChargerStatus");
//                    this.OnChargerStatusChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumAllPlaces", DbType="Int NOT NULL")]
//        public int NumAllPlaces
//        {
//            get
//            {
//                return this._NumAllPlaces;
//            }
//            set
//            {
//                if ((this._NumAllPlaces != value))
//                {
//                    this.OnNumAllPlacesChanging(value);
//                    this.SendPropertyChanging();
//                    this._NumAllPlaces = value;
//                    this.SendPropertyChanged("NumAllPlaces");
//                    this.OnNumAllPlacesChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumEmptyPlaces", DbType="Int NOT NULL")]
//        public int NumEmptyPlaces
//        {
//            get
//            {
//                return this._NumEmptyPlaces;
//            }
//            set
//            {
//                if ((this._NumEmptyPlaces != value))
//                {
//                    this.OnNumEmptyPlacesChanging(value);
//                    this.SendPropertyChanging();
//                    this._NumEmptyPlaces = value;
//                    this.SendPropertyChanged("NumEmptyPlaces");
//                    this.OnNumEmptyPlacesChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOrderPlaces", DbType="Int NOT NULL")]
//        public int NumOrderPlaces
//        {
//            get
//            {
//                return this._NumOrderPlaces;
//            }
//            set
//            {
//                if ((this._NumOrderPlaces != value))
//                {
//                    this.OnNumOrderPlacesChanging(value);
//                    this.SendPropertyChanging();
//                    this._NumOrderPlaces = value;
//                    this.SendPropertyChanged("NumOrderPlaces");
//                    this.OnNumOrderPlacesChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Charger_ChargingNow", Storage="_ChargingNows", ThisKey="ID_Charger", OtherKey="ID_Charger")]
//        public EntitySet<ChargingNows> ChargingNows
//        {
//            get
//            {
//                return this._ChargingNows;
//            }
//            set
//            {
//                this._ChargingNows.Assign(value);
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Charger_Order", Storage="_Orders", ThisKey="ID_Charger", OtherKey="ID_Charger")]
//        public EntitySet<Orders> Orders
//        {
//            get
//            {
//                return this._Orders;
//            }
//            set
//            {
//                this._Orders.Assign(value);
//            }
//        }
		
//        public event PropertyChangingEventHandler PropertyChanging;
		
//        public event PropertyChangedEventHandler PropertyChanged;
		
//        protected virtual void SendPropertyChanging()
//        {
//            if ((this.PropertyChanging != null))
//            {
//                this.PropertyChanging(this, emptyChangingEventArgs);
//            }
//        }
		
//        protected virtual void SendPropertyChanged(String propertyName)
//        {
//            if ((this.PropertyChanged != null))
//            {
//                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//            }
//        }
		
//        private void attach_ChargingNows(ChargingNows entity)
//        {
//            this.SendPropertyChanging();
//            entity.Charger = this;
//        }
		
//        private void detach_ChargingNows(ChargingNows entity)
//        {
//            this.SendPropertyChanging();
//            entity.Charger = null;
//        }
		
//        private void attach_Orders(Orders entity)
//        {
//            this.SendPropertyChanging();
//            entity.Chargers = this;
//        }
		
//        private void detach_Orders(Orders entity)
//        {
//            this.SendPropertyChanging();
//            entity.Chargers = null;
//        }
//    }
	
//    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChargingNow")]
//    public partial class ChargingNows : INotifyPropertyChanging, INotifyPropertyChanged
//    {
		
//        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//        private int _ID_Charging;
		
//        private int _ID_Driver;
		
//        private int _ID_Car;
		
//        private int _ID_Charger;
		
//        private double _ProbabilitySecond;
		
//        private System.DateTime _TimeStartCharging;
		
//        private System.DateTime _TimeEndChargingExpect;
		
//        private EntityRef<Chargers> _Charger;
		
//        private EntityRef<Drivers> _Driver;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnID_ChargingChanging(int value);
//    partial void OnID_ChargingChanged();
//    partial void OnID_DriverChanging(int value);
//    partial void OnID_DriverChanged();
//    partial void OnID_CarChanging(int value);
//    partial void OnID_CarChanged();
//    partial void OnID_ChargerChanging(int value);
//    partial void OnID_ChargerChanged();
//    partial void OnProbabilitySecondChanging(double value);
//    partial void OnProbabilitySecondChanged();
//    partial void OnTimeStartChargingChanging(System.DateTime value);
//    partial void OnTimeStartChargingChanged();
//    partial void OnTimeEndChargingExpectChanging(System.DateTime value);
//    partial void OnTimeEndChargingExpectChanged();
//    #endregion
		
//        public ChargingNows()
//        {
//            this._Charger = default(EntityRef<Chargers>);
//            this._Driver = default(EntityRef<Drivers>);
//            OnCreated();
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Charging", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//        public int ID_Charging
//        {
//            get
//            {
//                return this._ID_Charging;
//            }
//            set
//            {
//                if ((this._ID_Charging != value))
//                {
//                    this.OnID_ChargingChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Charging = value;
//                    this.SendPropertyChanged("ID_Charging");
//                    this.OnID_ChargingChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Driver", DbType="Int NOT NULL")]
//        public int ID_Driver
//        {
//            get
//            {
//                return this._ID_Driver;
//            }
//            set
//            {
//                if ((this._ID_Driver != value))
//                {
//                    if (this._Driver.HasLoadedOrAssignedValue)
//                    {
//                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//                    }
//                    this.OnID_DriverChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Driver = value;
//                    this.SendPropertyChanged("ID_Driver");
//                    this.OnID_DriverChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Car", DbType="Int NOT NULL")]
//        public int ID_Car
//        {
//            get
//            {
//                return this._ID_Car;
//            }
//            set
//            {
//                if ((this._ID_Car != value))
//                {
//                    this.OnID_CarChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Car = value;
//                    this.SendPropertyChanged("ID_Car");
//                    this.OnID_CarChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Charger", DbType="Int NOT NULL")]
//        public int ID_Charger
//        {
//            get
//            {
//                return this._ID_Charger;
//            }
//            set
//            {
//                if ((this._ID_Charger != value))
//                {
//                    if (this._Charger.HasLoadedOrAssignedValue)
//                    {
//                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//                    }
//                    this.OnID_ChargerChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Charger = value;
//                    this.SendPropertyChanged("ID_Charger");
//                    this.OnID_ChargerChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbabilitySecond", DbType="Float NOT NULL")]
//        public double ProbabilitySecond
//        {
//            get
//            {
//                return this._ProbabilitySecond;
//            }
//            set
//            {
//                if ((this._ProbabilitySecond != value))
//                {
//                    this.OnProbabilitySecondChanging(value);
//                    this.SendPropertyChanging();
//                    this._ProbabilitySecond = value;
//                    this.SendPropertyChanged("ProbabilitySecond");
//                    this.OnProbabilitySecondChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStartCharging", DbType="DateTime NOT NULL")]
//        public System.DateTime TimeStartCharging
//        {
//            get
//            {
//                return this._TimeStartCharging;
//            }
//            set
//            {
//                if ((this._TimeStartCharging != value))
//                {
//                    this.OnTimeStartChargingChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeStartCharging = value;
//                    this.SendPropertyChanged("TimeStartCharging");
//                    this.OnTimeStartChargingChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEndChargingExpect", DbType="DateTime NOT NULL")]
//        public System.DateTime TimeEndChargingExpect
//        {
//            get
//            {
//                return this._TimeEndChargingExpect;
//            }
//            set
//            {
//                if ((this._TimeEndChargingExpect != value))
//                {
//                    this.OnTimeEndChargingExpectChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeEndChargingExpect = value;
//                    this.SendPropertyChanged("TimeEndChargingExpect");
//                    this.OnTimeEndChargingExpectChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Charger_ChargingNow", Storage="_Charger", ThisKey="ID_Charger", OtherKey="ID_Charger", IsForeignKey=true)]
//        public Chargers Charger
//        {
//            get
//            {
//                return this._Charger.Entity;
//            }
//            set
//            {
//                Chargers previousValue = this._Charger.Entity;
//                if (((previousValue != value) 
//                            || (this._Charger.HasLoadedOrAssignedValue == false)))
//                {
//                    this.SendPropertyChanging();
//                    if ((previousValue != null))
//                    {
//                        this._Charger.Entity = null;
//                        previousValue.ChargingNows.Remove(this);
//                    }
//                    this._Charger.Entity = value;
//                    if ((value != null))
//                    {
//                        value.ChargingNows.Add(this);
//                        this._ID_Charger = value.ID_Charger;
//                    }
//                    else
//                    {
//                        this._ID_Charger = default(int);
//                    }
//                    this.SendPropertyChanged("Charger");
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_ChargingNow", Storage="_Driver", ThisKey="ID_Driver", OtherKey="ID_Driver", IsForeignKey=true)]
//        public Drivers Driver
//        {
//            get
//            {
//                return this._Driver.Entity;
//            }
//            set
//            {
//                Drivers previousValue = this._Driver.Entity;
//                if (((previousValue != value) 
//                            || (this._Driver.HasLoadedOrAssignedValue == false)))
//                {
//                    this.SendPropertyChanging();
//                    if ((previousValue != null))
//                    {
//                        this._Driver.Entity = null;
//                        previousValue.ChargingNows.Remove(this);
//                    }
//                    this._Driver.Entity = value;
//                    if ((value != null))
//                    {
//                        value.ChargingNows.Add(this);
//                        this._ID_Driver = value.ID_Driver;
//                    }
//                    else
//                    {
//                        this._ID_Driver = default(int);
//                    }
//                    this.SendPropertyChanged("Driver");
//                }
//            }
//        }
		
//        public event PropertyChangingEventHandler PropertyChanging;
		
//        public event PropertyChangedEventHandler PropertyChanged;
		
//        protected virtual void SendPropertyChanging()
//        {
//            if ((this.PropertyChanging != null))
//            {
//                this.PropertyChanging(this, emptyChangingEventArgs);
//            }
//        }
		
//        protected virtual void SendPropertyChanged(String propertyName)
//        {
//            if ((this.PropertyChanged != null))
//            {
//                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//            }
//        }
//    }
	
//    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Drivers")]
//    public partial class Drivers : INotifyPropertyChanging, INotifyPropertyChanged
//    {
		
//        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//        private int _ID_Driver;
		
//        private string _DriverName;
		
//        private string _DriverLogin;
		
//        private string _DriverPassword;
		
//        private int _Age;
		
//        private string _DriverStatus;
		
//        private double _Probability;
		
//        private EntitySet<Cars> _Cars;
		
//        private EntitySet<ChargingNows> _ChargingNows;
		
//        private EntitySet<Orders> _Orders;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnID_DriverChanging(int value);
//    partial void OnID_DriverChanged();
//    partial void OnDriverNameChanging(string value);
//    partial void OnDriverNameChanged();
//    partial void OnDriverLoginChanging(string value);
//    partial void OnDriverLoginChanged();
//    partial void OnDriverPasswordChanging(string value);
//    partial void OnDriverPasswordChanged();
//    partial void OnAgeChanging(int value);
//    partial void OnAgeChanged();
//    partial void OnDriverStatusChanging(string value);
//    partial void OnDriverStatusChanged();
//    partial void OnProbabilityChanging(double value);
//    partial void OnProbabilityChanged();
//    #endregion
		
//        public Drivers()
//        {
//            this._Cars = new EntitySet<Cars>(new Action<Cars>(this.attach_Cars), new Action<Cars>(this.detach_Cars));
//            this._ChargingNows = new EntitySet<ChargingNows>(new Action<ChargingNows>(this.attach_ChargingNows), new Action<ChargingNows>(this.detach_ChargingNows));
//            this._Orders = new EntitySet<Orders>(new Action<Orders>(this.attach_Orders), new Action<Orders>(this.detach_Orders));
//            OnCreated();
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Driver", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//        public int ID_Driver
//        {
//            get
//            {
//                return this._ID_Driver;
//            }
//            set
//            {
//                if ((this._ID_Driver != value))
//                {
//                    this.OnID_DriverChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Driver = value;
//                    this.SendPropertyChanged("ID_Driver");
//                    this.OnID_DriverChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverName", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
//        public string DriverName
//        {
//            get
//            {
//                return this._DriverName;
//            }
//            set
//            {
//                if ((this._DriverName != value))
//                {
//                    this.OnDriverNameChanging(value);
//                    this.SendPropertyChanging();
//                    this._DriverName = value;
//                    this.SendPropertyChanged("DriverName");
//                    this.OnDriverNameChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverLogin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string DriverLogin
//        {
//            get
//            {
//                return this._DriverLogin;
//            }
//            set
//            {
//                if ((this._DriverLogin != value))
//                {
//                    this.OnDriverLoginChanging(value);
//                    this.SendPropertyChanging();
//                    this._DriverLogin = value;
//                    this.SendPropertyChanged("DriverLogin");
//                    this.OnDriverLoginChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string DriverPassword
//        {
//            get
//            {
//                return this._DriverPassword;
//            }
//            set
//            {
//                if ((this._DriverPassword != value))
//                {
//                    this.OnDriverPasswordChanging(value);
//                    this.SendPropertyChanging();
//                    this._DriverPassword = value;
//                    this.SendPropertyChanged("DriverPassword");
//                    this.OnDriverPasswordChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
//        public int Age
//        {
//            get
//            {
//                return this._Age;
//            }
//            set
//            {
//                if ((this._Age != value))
//                {
//                    this.OnAgeChanging(value);
//                    this.SendPropertyChanging();
//                    this._Age = value;
//                    this.SendPropertyChanged("Age");
//                    this.OnAgeChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverStatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
//        public string DriverStatus
//        {
//            get
//            {
//                return this._DriverStatus;
//            }
//            set
//            {
//                if ((this._DriverStatus != value))
//                {
//                    this.OnDriverStatusChanging(value);
//                    this.SendPropertyChanging();
//                    this._DriverStatus = value;
//                    this.SendPropertyChanged("DriverStatus");
//                    this.OnDriverStatusChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Probability", DbType="Float NOT NULL")]
//        public double Probability
//        {
//            get
//            {
//                return this._Probability;
//            }
//            set
//            {
//                if ((this._Probability != value))
//                {
//                    this.OnProbabilityChanging(value);
//                    this.SendPropertyChanging();
//                    this._Probability = value;
//                    this.SendPropertyChanged("Probability");
//                    this.OnProbabilityChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_Car", Storage="_Cars", ThisKey="ID_Driver", OtherKey="ID_Driver")]
//        public EntitySet<Cars> Cars
//        {
//            get
//            {
//                return this._Cars;
//            }
//            set
//            {
//                this._Cars.Assign(value);
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_ChargingNow", Storage="_ChargingNows", ThisKey="ID_Driver", OtherKey="ID_Driver")]
//        public EntitySet<ChargingNows> ChargingNows
//        {
//            get
//            {
//                return this._ChargingNows;
//            }
//            set
//            {
//                this._ChargingNows.Assign(value);
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_Order", Storage="_Orders", ThisKey="ID_Driver", OtherKey="ID_Driver")]
//        public EntitySet<Orders> Orders
//        {
//            get
//            {
//                return this._Orders;
//            }
//            set
//            {
//                this._Orders.Assign(value);
//            }
//        }
		
//        public event PropertyChangingEventHandler PropertyChanging;
		
//        public event PropertyChangedEventHandler PropertyChanged;
		
//        protected virtual void SendPropertyChanging()
//        {
//            if ((this.PropertyChanging != null))
//            {
//                this.PropertyChanging(this, emptyChangingEventArgs);
//            }
//        }
		
//        protected virtual void SendPropertyChanged(String propertyName)
//        {
//            if ((this.PropertyChanged != null))
//            {
//                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//            }
//        }
		
//        private void attach_Cars(Cars entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = this;
//        }
		
//        private void detach_Cars(Cars entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = null;
//        }
		
//        private void attach_ChargingNows(ChargingNows entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = this;
//        }
		
//        private void detach_ChargingNows(ChargingNows entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = null;
//        }
		
//        private void attach_Orders(Orders entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = this;
//        }
		
//        private void detach_Orders(Orders entity)
//        {
//            this.SendPropertyChanging();
//            entity.Driver = null;
//        }
//    }
	
//    [global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
//    public partial class Orders : INotifyPropertyChanging, INotifyPropertyChanged
//    {
		
//        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//        private int _ID_Order;
		
//        private int _ID_Driver;
		
//        private int _ID_Car;
		
//        private int _ID_Charger;
		
//        private string _OrderStatus;
		
//        private System.DateTime _OrderTime;
		
//        private System.DateTime _TimeStartChargingExpect;
		
//        private double _TimeChargingExpect;
		
//        private System.Nullable<System.DateTime> _TimeStartCharging;
		
//        private System.Nullable<System.DateTime> _TimeEndCharging;
		
//        private System.Nullable<double> _TimeCharging;
		
//        private System.Nullable<double> _Kilowatt;
		
//        private double _ProbabilityOrder;
		
//        private EntityRef<Chargers> _Charger;
		
//        private EntityRef<Drivers> _Driver;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnID_OrderChanging(int value);
//    partial void OnID_OrderChanged();
//    partial void OnID_DriverChanging(int value);
//    partial void OnID_DriverChanged();
//    partial void OnID_CarChanging(int value);
//    partial void OnID_CarChanged();
//    partial void OnID_ChargerChanging(int value);
//    partial void OnID_ChargerChanged();
//    partial void OnOrderStatusChanging(string value);
//    partial void OnOrderStatusChanged();
//    partial void OnOrderTimeChanging(System.DateTime value);
//    partial void OnOrderTimeChanged();
//    partial void OnTimeStartChargingExpectChanging(System.DateTime value);
//    partial void OnTimeStartChargingExpectChanged();
//    partial void OnTimeChargingExpectChanging(double value);
//    partial void OnTimeChargingExpectChanged();
//    partial void OnTimeStartChargingChanging(System.Nullable<System.DateTime> value);
//    partial void OnTimeStartChargingChanged();
//    partial void OnTimeEndChargingChanging(System.Nullable<System.DateTime> value);
//    partial void OnTimeEndChargingChanged();
//    partial void OnTimeChargingChanging(System.Nullable<double> value);
//    partial void OnTimeChargingChanged();
//    partial void OnKilowattChanging(System.Nullable<double> value);
//    partial void OnKilowattChanged();
//    partial void OnProbabilityOrderChanging(double value);
//    partial void OnProbabilityOrderChanged();
//    #endregion
		
//        public Orders()
//        {
//            this._Charger = default(EntityRef<Chargers>);
//            this._Driver = default(EntityRef<Drivers>);
//            OnCreated();
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Order", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//        public int ID_Order
//        {
//            get
//            {
//                return this._ID_Order;
//            }
//            set
//            {
//                if ((this._ID_Order != value))
//                {
//                    this.OnID_OrderChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Order = value;
//                    this.SendPropertyChanged("ID_Order");
//                    this.OnID_OrderChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Driver", DbType="Int NOT NULL")]
//        public int ID_Driver
//        {
//            get
//            {
//                return this._ID_Driver;
//            }
//            set
//            {
//                if ((this._ID_Driver != value))
//                {
//                    if (this._Driver.HasLoadedOrAssignedValue)
//                    {
//                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//                    }
//                    this.OnID_DriverChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Driver = value;
//                    this.SendPropertyChanged("ID_Driver");
//                    this.OnID_DriverChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Car", DbType="Int NOT NULL")]
//        public int ID_Car
//        {
//            get
//            {
//                return this._ID_Car;
//            }
//            set
//            {
//                if ((this._ID_Car != value))
//                {
//                    this.OnID_CarChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Car = value;
//                    this.SendPropertyChanged("ID_Car");
//                    this.OnID_CarChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Charger", DbType="Int NOT NULL")]
//        public int ID_Charger
//        {
//            get
//            {
//                return this._ID_Charger;
//            }
//            set
//            {
//                if ((this._ID_Charger != value))
//                {
//                    if (this._Charger.HasLoadedOrAssignedValue)
//                    {
//                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//                    }
//                    this.OnID_ChargerChanging(value);
//                    this.SendPropertyChanging();
//                    this._ID_Charger = value;
//                    this.SendPropertyChanged("ID_Charger");
//                    this.OnID_ChargerChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatus", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
//        public string OrderStatus
//        {
//            get
//            {
//                return this._OrderStatus;
//            }
//            set
//            {
//                if ((this._OrderStatus != value))
//                {
//                    this.OnOrderStatusChanging(value);
//                    this.SendPropertyChanging();
//                    this._OrderStatus = value;
//                    this.SendPropertyChanged("OrderStatus");
//                    this.OnOrderStatusChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderTime", DbType="DateTime NOT NULL")]
//        public System.DateTime OrderTime
//        {
//            get
//            {
//                return this._OrderTime;
//            }
//            set
//            {
//                if ((this._OrderTime != value))
//                {
//                    this.OnOrderTimeChanging(value);
//                    this.SendPropertyChanging();
//                    this._OrderTime = value;
//                    this.SendPropertyChanged("OrderTime");
//                    this.OnOrderTimeChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStartChargingExpect", DbType="DateTime NOT NULL")]
//        public System.DateTime TimeStartChargingExpect
//        {
//            get
//            {
//                return this._TimeStartChargingExpect;
//            }
//            set
//            {
//                if ((this._TimeStartChargingExpect != value))
//                {
//                    this.OnTimeStartChargingExpectChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeStartChargingExpect = value;
//                    this.SendPropertyChanged("TimeStartChargingExpect");
//                    this.OnTimeStartChargingExpectChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeChargingExpect", DbType="Float NOT NULL")]
//        public double TimeChargingExpect
//        {
//            get
//            {
//                return this._TimeChargingExpect;
//            }
//            set
//            {
//                if ((this._TimeChargingExpect != value))
//                {
//                    this.OnTimeChargingExpectChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeChargingExpect = value;
//                    this.SendPropertyChanged("TimeChargingExpect");
//                    this.OnTimeChargingExpectChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStartCharging", DbType="DateTime")]
//        public System.Nullable<System.DateTime> TimeStartCharging
//        {
//            get
//            {
//                return this._TimeStartCharging;
//            }
//            set
//            {
//                if ((this._TimeStartCharging != value))
//                {
//                    this.OnTimeStartChargingChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeStartCharging = value;
//                    this.SendPropertyChanged("TimeStartCharging");
//                    this.OnTimeStartChargingChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEndCharging", DbType="DateTime")]
//        public System.Nullable<System.DateTime> TimeEndCharging
//        {
//            get
//            {
//                return this._TimeEndCharging;
//            }
//            set
//            {
//                if ((this._TimeEndCharging != value))
//                {
//                    this.OnTimeEndChargingChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeEndCharging = value;
//                    this.SendPropertyChanged("TimeEndCharging");
//                    this.OnTimeEndChargingChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCharging", DbType="Float")]
//        public System.Nullable<double> TimeCharging
//        {
//            get
//            {
//                return this._TimeCharging;
//            }
//            set
//            {
//                if ((this._TimeCharging != value))
//                {
//                    this.OnTimeChargingChanging(value);
//                    this.SendPropertyChanging();
//                    this._TimeCharging = value;
//                    this.SendPropertyChanged("TimeCharging");
//                    this.OnTimeChargingChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilowatt", DbType="Float")]
//        public System.Nullable<double> Kilowatt
//        {
//            get
//            {
//                return this._Kilowatt;
//            }
//            set
//            {
//                if ((this._Kilowatt != value))
//                {
//                    this.OnKilowattChanging(value);
//                    this.SendPropertyChanging();
//                    this._Kilowatt = value;
//                    this.SendPropertyChanged("Kilowatt");
//                    this.OnKilowattChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbabilityOrder", DbType="Float NOT NULL")]
//        public double ProbabilityOrder
//        {
//            get
//            {
//                return this._ProbabilityOrder;
//            }
//            set
//            {
//                if ((this._ProbabilityOrder != value))
//                {
//                    this.OnProbabilityOrderChanging(value);
//                    this.SendPropertyChanging();
//                    this._ProbabilityOrder = value;
//                    this.SendPropertyChanged("ProbabilityOrder");
//                    this.OnProbabilityOrderChanged();
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Charger_Order", Storage="_Charger", ThisKey="ID_Charger", OtherKey="ID_Charger", IsForeignKey=true)]
//        public Chargers Chargers
//        {
//            get
//            {
//                return this._Charger.Entity;
//            }
//            set
//            {
//                Chargers previousValue = this._Charger.Entity;
//                if (((previousValue != value) 
//                            || (this._Charger.HasLoadedOrAssignedValue == false)))
//                {
//                    this.SendPropertyChanging();
//                    if ((previousValue != null))
//                    {
//                        this._Charger.Entity = null;
//                        previousValue.Orders.Remove(this);
//                    }
//                    this._Charger.Entity = value;
//                    if ((value != null))
//                    {
//                        value.Orders.Add(this);
//                        this._ID_Charger = value.ID_Charger;
//                    }
//                    else
//                    {
//                        this._ID_Charger = default(int);
//                    }
//                    this.SendPropertyChanged("Charger");
//                }
//            }
//        }
		
//        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Driver_Order", Storage="_Driver", ThisKey="ID_Driver", OtherKey="ID_Driver", IsForeignKey=true)]
//        public Drivers Driver
//        {
//            get
//            {
//                return this._Driver.Entity;
//            }
//            set
//            {
//                Drivers previousValue = this._Driver.Entity;
//                if (((previousValue != value) 
//                            || (this._Driver.HasLoadedOrAssignedValue == false)))
//                {
//                    this.SendPropertyChanging();
//                    if ((previousValue != null))
//                    {
//                        this._Driver.Entity = null;
//                        previousValue.Orders.Remove(this);
//                    }
//                    this._Driver.Entity = value;
//                    if ((value != null))
//                    {
//                        value.Orders.Add(this);
//                        this._ID_Driver = value.ID_Driver;
//                    }
//                    else
//                    {
//                        this._ID_Driver = default(int);
//                    }
//                    this.SendPropertyChanged("Driver");
//                }
//            }
//        }
		
//        public event PropertyChangingEventHandler PropertyChanging;
		
//        public event PropertyChangedEventHandler PropertyChanged;
		
//        protected virtual void SendPropertyChanging()
//        {
//            if ((this.PropertyChanging != null))
//            {
//                this.PropertyChanging(this, emptyChangingEventArgs);
//            }
//        }
		
//        protected virtual void SendPropertyChanged(String propertyName)
//        {
//            if ((this.PropertyChanged != null))
//            {
//                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//            }
//        }
//    }
//}
//#pragma warning restore 1591
