//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCharging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public int ID_Driver { get; set; }
        public int ID_Car { get; set; }
        public int ID_Charger { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime OrderTime { get; set; }
        public System.DateTime TimeStartChargingExpect { get; set; }
        public double TimeChargingExpect { get; set; }
        public Nullable<System.DateTime> TimeStartCharging { get; set; }
        public Nullable<System.DateTime> TimeEndCharging { get; set; }
        public Nullable<double> TimeCharging { get; set; }
        public Nullable<double> Kilowatt { get; set; }
        public double ProbabilityOrder { get; set; }
    
        public virtual Chargers Chargers { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
